# Generated by Django 4.2.21 on 2025-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_at_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('yüksek', 'Yüksek'), ('orta', 'Orta'), ('düşük', 'Düşük')], default='orta', max_length=10),
        ),
    ]
